# Natural Language Processing with Amazon Reviews

Developed for the second project of the Artificial Intelligence course

## Setup and Environment

After installing Python and the necessary packages, run the following code to import them:

In [52]:
%matplotlib inline

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression, Perceptron
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import PredefinedSplit
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

MAX_FEATURES = 10000

## Implementation work

### Generating a data set
#### Obtaining features from the Bag-of-Words model

In [ ]:
train = pd.read_csv('./data/train_preprocessed.csv')
test = pd.read_csv('./data/test_preprocessed.csv')

Please choose one of the following vectorizers:
#### Creating regular CountVectorizers (default)

In [ ]:
titleVectorizer = CountVectorizer(max_features=MAX_FEATURES)
textVectorizer = CountVectorizer(max_features=MAX_FEATURES)

#### Creating 1-hot vectors

In [ ]:
titleVectorizer = CountVectorizer(binary=True, max_features=MAX_FEATURES)
textVectorizer = CountVectorizer(binary=True, max_features=MAX_FEATURES)

#### Creating TF-IDF vectors

In [ ]:
titleVectorizer = TfidfVectorizer(max_features=MAX_FEATURES)
textVectorizer = TfidfVectorizer(max_features=MAX_FEATURES)

#### Creating bi-gram CountVectorizors

In [ ]:
titleVectorizer = CountVectorizer(ngram_range=(1, 2), max_features=MAX_FEATURES)
textVectorizer = CountVectorizer(ngram_range=(1, 2), max_features=MAX_FEATURES)

#### Creating bi-gram TF-IDF vectors

In [ ]:
titleVectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=MAX_FEATURES)
textVectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=MAX_FEATURES)

#### Creating tri-gram TF-IDF vectors

In [ ]:
titleVectorizer = TfidfVectorizer(ngram_range=(1, 3), max_features=MAX_FEATURES)
textVectorizer = TfidfVectorizer(ngram_range=(1, 3), max_features=MAX_FEATURES)

#### Transforming the dataset

In [53]:
trainTitleArr = list(map(str, train['review_title']))
trainTextArr = list(map(str, train['review_text']))

titleWords = titleVectorizer.fit_transform(trainTitleArr).toarray()
textWords = textVectorizer.fit_transform(trainTextArr).toarray()

allWords = np.array([np.concatenate((titleWords[i], textWords[i])) for i in range(len(titleWords))])

print(titleWords.shape)
print(textWords.shape)
print(allWords.shape)

y = train['class_index']

# Test variables
testTitleArr = list(map(str, test['review_title']))
testTextArr = list(map(str, test['review_text']))

testTitleVector = titleVectorizer.transform(testTitleArr).toarray()
testTextVector = textVectorizer.transform(testTextArr).toarray()

testAllWords = np.array([np.concatenate((testTitleVector[i], testTextVector[i])) for i in range(len(testTitleVector))])

(5000, 10000)
(5000, 10000)
(5000, 20000)


### Prediction after searching parameters in grid

In [58]:
#param_grid = {"alpha": [0.005, 0.01, 0.05], "penalty": ['l2', 'l1', 'elasticnet', None]}
def gridPredict(clf, param_grid, **arg):
    grid = GridSearchCV(clf, param_grid) # If we want Cross Validation: cv=pdfsplt

    grid.fit(allWords, y, **arg)

    print("Best grid params:", grid.best_params_)

    return grid.predict(testAllWords)

### Training Classifiers and Prediction

In [ ]:
def predict(clf, **arg):
    # Train with allWords
    clf.fit(allWords, y, **arg)

    return clf.predict(testAllWords)

# MultinomialNB()

### Analyse Results

In [55]:
def analyze(prediction, test):
    y_test = test['class_index']

    # confusion matrix
    confusionMatrix = confusion_matrix(y_test, prediction)
    print("Confusion Matrix:")
    print(confusionMatrix)

    accuracy = accuracy_score(y_test, prediction)

    print("Accuracy: ", accuracy * 100, " %")
    print("Precision: ", precision_score(y_test, prediction, average='weighted') * 100, " %")
    print('Recall: ', recall_score(y_test, prediction, average='weighted') * 100, " %")
    print('F1: ', f1_score(y_test, prediction, average='weighted') * 100, " %")

### K-Nearest Neighbor (K = 5)

In [ ]:
prediction = predict(KNeighborsClassifier(n_neighbors=5))
print("K-Nearest Neighbor Results:")
analyze(prediction, test)

### Multinomial Naive Bays

In [64]:
# prediction = predict(MultinomialNB(), sample_weight=1.0)
gridPrediction = gridPredict(MultinomialNB(), {"alpha": [0.0001, 0.5, 1.0]}, sample_weight=1.0)
print("MultinomialNB Results:")
analyze(prediction, test)

Best grid params: {'alpha': 1.0}
MultinomialNB Results:
Confusion Matrix:
[[106  48  24  15   7]
 [ 57  64  45  27   7]
 [ 18  49  83  37  13]
 [  6  17  47  73  57]
 [  8   7  17  59 109]]
Accuracy:  43.5  %
Precision:  43.69066704308459  %
Recall:  43.5  %
F1:  43.56306754905318  %


### Random Forest

In [70]:
#prediction = predict(RandomForestClassifier(), sample_weight=1.0) 
# "max_features": ["int", "sqrt", "log2"]
prediction = gridPredict(RandomForestClassifier(), {"n_estimators": [50, 100, 200]} , sample_weight=1.0)
print("RandomForestClassifier Results:")
analyze(prediction, test)

KeyboardInterrupt: 

### Decision Tree

In [ ]:
prediction = predict(DecisionTreeClassifier(), sample_weight=1.0)
print("DecisionTreeClassifier Results:")
analyze(prediction, test)

### Perceptron

In [ ]:
prediction = predict(Perceptron(), sample_weight=1.0)
print("Perceptron Results:")
analyze(prediction, test)

### Logistic Regression

In [ ]:
prediction = predict(LogisticRegression(), sample_weight=1.0)
print("LogisticRegression Results:")
analyze(prediction, test)

### Linear SVC

In [ ]:
prediction = predict(LinearSVC(), sample_weight=1.0)
print("LinearSVC Results:")
analyze(prediction, test)

### Neural Network (Multi-Layer Perceptron)

In [ ]:
prediction = predict(MLPClassifier())
print("NeuralNetwork Results:")
analyze(prediction, test)