# Natural Language Processing with Amazon Reviews

Developed for the second project of the Artificial Intelligence course

## Setup and Environment

After installing Python and the necessary packages, run the following code to import them:

In [44]:
%matplotlib inline

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression, Perceptron
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import PredefinedSplit
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV

MAX_FEATURES = 8000

## Implementation work

### Generating a data set
#### Obtaining features from the Bag-of-Words model

In [45]:
train = pd.read_csv('./data/train_preprocessed50k.csv')
test = pd.read_csv('./data/test_preprocessed50k.csv')

Please choose one of the following vectorizers:
#### Creating regular CountVectorizers (default)

In [43]:
titleVectorizer = CountVectorizer(max_features=MAX_FEATURES)
textVectorizer = CountVectorizer(max_features=MAX_FEATURES)

#### Creating 1-hot vectors

In [14]:
titleVectorizer = CountVectorizer(binary=True, max_features=MAX_FEATURES)
textVectorizer = CountVectorizer(binary=True, max_features=MAX_FEATURES)

#### Creating TF-IDF vectors

In [ ]:
titleVectorizer = TfidfVectorizer(max_features=MAX_FEATURES)
textVectorizer = TfidfVectorizer(max_features=MAX_FEATURES)

#### Creating bi-gram CountVectorizors

In [21]:
titleVectorizer = CountVectorizer(ngram_range=(1, 2), max_features=MAX_FEATURES)
textVectorizer = CountVectorizer(ngram_range=(1, 2), max_features=MAX_FEATURES)

#### Creating bi-gram TF-IDF vectors

In [46]:
titleVectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=MAX_FEATURES)
textVectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=MAX_FEATURES)

#### Creating tri-gram CountVectorizors

In [27]:
titleVectorizer = CountVectorizer(ngram_range=(1, 3), max_features=MAX_FEATURES)
textVectorizer = CountVectorizer(ngram_range=(1, 3), max_features=MAX_FEATURES)

#### Creating tri-gram TF-IDF vectors

In [ ]:
titleVectorizer = TfidfVectorizer(ngram_range=(1, 3), max_features=MAX_FEATURES)
textVectorizer = TfidfVectorizer(ngram_range=(1, 3), max_features=MAX_FEATURES)

#### Transforming the dataset

In [47]:
trainTitleArr = list(map(str, train['review_title']))
trainTextArr = list(map(str, train['review_text']))

titleWords = titleVectorizer.fit_transform(trainTitleArr).toarray()
textWords = textVectorizer.fit_transform(trainTextArr).toarray()

allWords = np.array([np.concatenate((titleWords[i], textWords[i])) for i in range(len(titleWords))])

print(titleWords.shape)
print(textWords.shape)
print(allWords.shape)

y = train['class_index']

# Test variables
testTitleArr = list(map(str, test['review_title']))
testTextArr = list(map(str, test['review_text']))

testTitleVector = titleVectorizer.transform(testTitleArr).toarray()
testTextVector = textVectorizer.transform(testTextArr).toarray()

testAllWords = np.array([np.concatenate((testTitleVector[i], testTextVector[i])) for i in range(len(testTitleVector))])

(50000, 8000)
(50000, 8000)
(50000, 16000)


### Training Classifiers and Prediction

In [48]:
def predict(clf, **arg):
    # Train with allWords
    clf.fit(allWords, y, **arg)

    return clf.predict(testAllWords)

### Splitting in 3 datasets: Train, Parameter Fine-Tuning and Test.

In [49]:
def fullPredict(clf, param_grid, **arg):
    # Splitting test dataset into test and parameter fine tuning
    X_train, X_paramTuning, y_train, y_paramTuning= train_test_split(allWords, y, test_size=0.3, random_state=0)
    
    # Train with allWords
    clf.fit(X_train, y_train, **arg)

    grid = HalvingGridSearchCV(clf, param_grid) # If we want Cross Validation: cv=pdfsplt

    grid.fit(X_paramTuning, y_paramTuning, **arg)

    print("Best grid params:", grid.best_params_)

    return grid.predict(testAllWords)

# MultinomialNB()

### Plot Methods

In [88]:
def prepare_statistic(data):
    x = ['Accuracy', 'Precision', 'Recall', 'F1']
    title = data.iloc[0]
    y = data.iloc[1:].tolist()
    return x, y, title

def plot_graph(data, figLabel):
    fig, axs = plt.subplots(2, 3, sharex=True, sharey=True)
    fig.set_figwidth(20)
    fig.set_figheight(7)
    fig.suptitle(figLabel)
    for i in range(2):
        for j in range(3):
            index = i*3 + j
            currData = data[index]
            x, y, title = prepare_statistic(currData)
            axis = axs[i, j]
            # axis.set_ylim(bottom=0.0, top=1.0)
            axis.bar(x, y)
            axis.set_title(title)
            axis.grid(True)
    plt.show()

### Analyze Results

In [89]:
def analyze(prediction, test, classifierLabel):
    y_test = test['class_index']

    # confusion matrix
    confusionMatrix = confusion_matrix(y_test, prediction)
    print("Confusion Matrix:")
    print(confusionMatrix)

    plot_data = []

    # Accuracy is a metric that takes into account all the classes
    accuracy = accuracy_score(y_test, prediction)
    precision = precision_score(y_test, prediction, average='weighted')
    recall = recall_score(y_test, prediction, average='weighted')
    f1 = f1_score(y_test, prediction, average='weighted')

    print("Accuracy: ", accuracy * 100, " %")
    print("Precision: ", precision * 100, " %")
    print('Recall: ', recall * 100, " %")
    print('F1: ', f1 * 100, " %")

    plot_data.append(pd.Series(['All Ratings', accuracy, precision, recall, f1]))
    
    # Calculate metrics for individual classes
    for class_index in range(1, 6, 1):
        precision = precision_score(y_test, prediction, average='weighted', labels=[class_index])
        recall = recall_score(y_test, prediction, average='weighted', labels=[class_index])
        f1 = f1_score(y_test, prediction, average='weighted', labels=[class_index])
        plot_data.append(pd.Series([str(class_index)+' Star Rating', accuracy, precision, recall, f1]))


    # Plot the data
    plot_graph(plot_data, classifierLabel)


### K-Nearest Neighbor

In [21]:
prediction = predict(KNeighborsClassifier(n_neighbors=5))
# prediction = fullPredict(KNeighborsClassifier(), {"n_neighbors": [5, 15, 30, 40], "leaf_size": [10, 20, 30, 35]})
print("K-Nearest Neighbor Results:")
analyze(prediction, test, "K-Nearest Neighbor")

Best grid params: {'leaf_size': 10, 'n_neighbors': 40}
K-Nearest Neighbor Results:
Confusion Matrix:
[[ 54  17  10  83  36]
 [ 29  30  17  97  27]
 [ 18  11  11 118  42]
 [  7  10   6 121  56]
 [  7   3   9  93  88]]
Accuracy:  30.4  %
Precision:  33.78778756177409  %
Recall:  30.4  %
F1:  27.661714033918283  %


### Multinomial Naive Bayes

In [90]:
prediction = predict(MultinomialNB(), sample_weight=1.0)
# prediction = gridPredict(MultinomialNB(), {"alpha": [0.0001, 0.5, 1.0]}, sample_weight=1.0)
# prediction = fullPredict(MultinomialNB(), {"alpha": [0.0001, 0.5, 1.0]}, sample_weight=1.0)
print("MultinomialNB Results:")
analyze(prediction, test, 'Multinomial Naive Bayes')

MultinomialNB Results:
Confusion Matrix:
[[1307  431  126   64   72]
 [ 519  829  457  123   72]
 [ 211  381  841  427  140]
 [  83   90  368  893  566]
 [  72   54   72  410 1392]]
Accuracy:  52.62  %
Precision:  51.97142801131355  %
Recall:  52.62  %
F1:  52.1833843820949  %


### Random Forest

In [ ]:
# prediction = predict(RandomForestClassifier(n_estimators=100), sample_weight=1.0) 
# "max_features": ["int", "sqrt", "log2"]
prediction = gridPredict(RandomForestClassifier(), {"n_estimators": [50, 100]} , sample_weight=1.0)
# TODO: TEST SINGLE PARAMETER (n_estimators = 200 ...)
print("RandomForestClassifier Results:")
analyze(prediction, test, 'Random Forest')

### Decision Tree

In [22]:
#prediction = predict(DecisionTreeClassifier(), sample_weight=1.0)
prediction = gridPredict(DecisionTreeClassifier(), {"criterion": ["gini", "entropy", "log_loss"], "splitter": ["best", "random"]} , sample_weight=1.0)
print("DecisionTreeClassifier Results:")
analyze(prediction, test, 'Decision Tree')

/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
4 fits failed out of a total of 12.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 937, in fit
    super().fit(
  File "/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

  warning

Best grid params: {'criterion': 'gini', 'splitter': 'best'}
DecisionTreeClassifier Results:
Confusion Matrix:
[[83 53 22 23 19]
 [55 43 47 33 22]
 [34 41 54 46 25]
 [17 23 49 58 53]
 [13 24 18 48 97]]
Accuracy:  33.5  %
Precision:  33.13434991037683  %
Recall:  33.5  %
F1:  33.289532259516896  %


### Perceptron

In [23]:
# prediction = predict(Perceptron(), sample_weight=1.0)
prediction = gridPredict(Perceptron(), {"alpha": [0.0001, 0.001]} , sample_weight=1.0)
print("Perceptron Results:")
analyze(prediction, test, 'Perceptron')

Best grid params: {'alpha': 0.0001}
Perceptron Results:
Confusion Matrix:
[[109  45  27   9  10]
 [ 51  80  30  30   9]
 [ 27  49  53  49  22]
 [ 21  16  27  83  53]
 [ 13  14  17  48 108]]
Accuracy:  43.3  %
Precision:  42.86348551441378  %
Recall:  43.3  %
F1:  42.935683522677394  %


### Logistic Regression

In [10]:
prediction = predict(LogisticRegression(), sample_weight=1.0)
# Best grid params: {'class_weight': 'balanced', 'solver': 'saga'} este foi o resultado do grid search
#prediction = gridPredict(LogisticRegression(), {#"penalty": ["l1", "l2", "elastic", "none"],
#    "class_weight": ["balanced", None], "solver": ["newton-cg", "lbfgs", "sag", "saga"]
#}, sample_weight=1.0)
print("LogisticRegression Results:")
analyze(prediction, test, 'Logistic Regression')

LogisticRegression Results:
Confusion Matrix:
[[121  41  22   7   9]
 [ 52  76  37  27   8]
 [ 28  48  60  43  21]
 [ 15  10  39  85  51]
 [  6  15  16  43 120]]
Accuracy:  46.2  %
Precision:  45.57338914038485  %
Recall:  46.2  %
F1:  45.8121814558217  %


/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### Linear SVC

In [15]:
prediction = predict(LinearSVC(), sample_weight=1.0)
# Best grid params: {'C': 0.2, 'class_weight': 'balanced', 'dual': True, 'loss': 'squared_hinge', 'multi_class': 'ovr'}
#prediction = gridPredict(LinearSVC(), {
#    "class_weight": ["balanced", None], "loss": ["hinge", "squared_hinge"], "multi_class": ["ovr", "crammer_singer"], "C": [0.2, 0.5, 1.0, 2.0], "dual": [True, False]
#}, sample_weight=1.0)
print("LinearSVC Results:")
analyze(prediction, test, 'Linear SVC')

/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/bruno/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinea

Best grid params: {'C': 0.2, 'class_weight': 'balanced', 'dual': True, 'loss': 'squared_hinge', 'multi_class': 'ovr'}
LinearSVC Results:
Confusion Matrix:
[[114  46  25   6   9]
 [ 55  71  35  29  10]
 [ 30  54  54  40  22]
 [ 14  10  37  82  57]
 [  9  11  17  44 119]]
Accuracy:  44.0  %
Precision:  43.2216209477584  %
Recall:  44.0  %
F1:  43.51456960807654  %


### Neural Network (Multi-Layer Perceptron)

In [ ]:
prediction = predict(MLPClassifier())
print("NeuralNetwork Results:")
analyze(prediction, test, 'Neural Network (Multi-Layer Perceptron)')